export const MOCK_EU_COUNTRIES = [
  'España',
  'Portugal',
  'Francia',
  'Italia',
  'Alemania',
  'Bélgica',
  'Países Bajos',
  'Luxemburgo',
  'Dinamarca',
  'Reino Unido',
  'Irlanda',
  'Grecia',
  'Finlandia',
  'Suecia',
  'Estonia']
